// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Boutique
    {
        public Boutique()
        {
            Inventaire = new HashSet<Inventaire>();
        }

        public int IdBoutique { get; set; }
        public string Nom { get; set; }

        public virtual ICollection<Inventaire> Inventaire { get; set; }
    }
}