// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class CompetenceChoix
    {
        public int IdAssociation { get; set; }
        public int IdCompetence { get; set; }
        public int? IdOrigine { get; set; }
        public int? IdMetier { get; set; }

        public virtual Competences IdCompetenceNavigation { get; set; }
        public virtual Metier IdMetierNavigation { get; set; }
        public virtual Origine IdOrigineNavigation { get; set; }
    }
}