// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Competences
    {
        public Competences()
        {
            CompetenceChoix = new HashSet<CompetenceChoix>();
            CompetenceHeritee = new HashSet<CompetenceHeritee>();
        }

        public int IdCompetence { get; set; }
        public string Nom { get; set; }

        public virtual ICollection<CompetenceChoix> CompetenceChoix { get; set; }
        public virtual ICollection<CompetenceHeritee> CompetenceHeritee { get; set; }
    }
}