// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Competences
    {
        public int IdCompetence { get; set; }
        public string Nom { get; set; }
    }
}