// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models
{
    public partial class Donjon
    {
        public Donjon()
        {
            GroupeMonstre = new HashSet<GroupeMonstre>();
        }

        public int IdDonjon { get; set; }
        public int Recompense { get; set; }

        public virtual ICollection<GroupeMonstre> GroupeMonstre { get; set; }
    }
}