// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models
{
    public partial class GroupeMonstre
    {
        public GroupeMonstre()
        {
            Monstre = new HashSet<Monstre>();
        }

        public int IdGroupeMonstre { get; set; }
        public int IdDonjon { get; set; }

        public virtual Donjon IdDonjonNavigation { get; set; }
        public virtual ICollection<Monstre> Monstre { get; set; }
    }
}