// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class GroupeItem
    {
        public GroupeItem()
        {
            TypeItem = new HashSet<TypeItem>();
        }

        public int IdGroupe { get; set; }
        public string Nom { get; set; }

        public virtual ICollection<TypeItem> TypeItem { get; set; }
    }
}