// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class GroupeMonstreJoueur
    {
        public int IdAssociation { get; set; }
        public int IdJoueur { get; set; }
        public int IdGroupeMonstre { get; set; }
        public sbyte EstBattu { get; set; }

        public virtual GroupeMonstre IdGroupeMonstreNavigation { get; set; }
        public virtual Joueur IdJoueurNavigation { get; set; }
    }
}