// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Item
    {
        public int IdItem { get; set; }
        public int IdInventaire { get; set; }
        public int IdTypeItem { get; set; }
        public int Quantite { get; set; }

        public virtual Inventaire IdInventaireNavigation { get; set; }
        public virtual TypeItem IdTypeItemNavigation { get; set; }
    }
}