// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Joueur
    {
        public Joueur()
        {
            Sauvegarde = new HashSet<Sauvegarde>();
        }

        public int IdJoueur { get; set; }
        public int IdRace { get; set; }
        public int IdInventaire { get; set; }
        public string Nom { get; set; }
        public int Experience { get; set; }
        public int Niveau { get; set; }
        public int Courage { get; set; }
        public int Intelligence { get; set; }
        public int Charisme { get; set; }
        public int Adresse { get; set; }
        public int Force { get; set; }
        public int Destin { get; set; }
        public int Debilibuck { get; set; }
        public int ManqueDeBol { get; set; }
        public int Or { get; set; }
        public int Argent { get; set; }

        public virtual Inventaire IdInventaireNavigation { get; set; }
        public virtual Origine IdRaceNavigation { get; set; }
        public virtual ICollection<Sauvegarde> Sauvegarde { get; set; }
    }
}