// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Map
    {
        public Map()
        {
            GroupeMonstre = new HashSet<GroupeMonstre>();
            Sauvegarde = new HashSet<Sauvegarde>();
        }

        public int IdMap { get; set; }
        public string Nom { get; set; }
        public string Url { get; set; }
        public int PositionSpawnX { get; set; }
        public int PositionSpawnY { get; set; }

        public virtual ICollection<GroupeMonstre> GroupeMonstre { get; set; }
        public virtual ICollection<Sauvegarde> Sauvegarde { get; set; }
    }
}