// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Map
    {
        public Map()
        {
            GroupeMonstre = new HashSet<GroupeMonstre>();
            Joueur = new HashSet<Joueur>();
        }

        public int IdMap { get; set; }
        public string Nom { get; set; }
        public string Filename { get; set; }
        public int PositionSpawnX { get; set; }
        public int PositionSpawnY { get; set; }

        public virtual ICollection<GroupeMonstre> GroupeMonstre { get; set; }
        public virtual ICollection<Joueur> Joueur { get; set; }
    }
}