// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class RaceMonstre
    {
        public RaceMonstre()
        {
            Monstre = new HashSet<Monstre>();
        }

        public int IdRaceMonstre { get; set; }
        public string Nom { get; set; }

        public virtual ICollection<Monstre> Monstre { get; set; }
    }
}