// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models
{
    public partial class RacePersonnage
    {
        public RacePersonnage()
        {
            Joueur = new HashSet<Joueur>();
        }

        public int IdRacePersonnage { get; set; }
        public string Nom { get; set; }

        public virtual ICollection<Joueur> Joueur { get; set; }
    }
}