// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class Sauvegarde
    {
        public int IdSauvegarde { get; set; }
        public int IdJoueur { get; set; }
        public int IdMapCourante { get; set; }

        public virtual Joueur IdJoueurNavigation { get; set; }
        public virtual Map IdMapCouranteNavigation { get; set; }
    }
}