// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService
{
    public partial class TypeItem
    {
        public TypeItem()
        {
            Item = new HashSet<Item>();
        }

        public int IdTypeItem { get; set; }
        public int IdGroupe { get; set; }
        public string Nom { get; set; }
        public int Prix { get; set; }
        public int Vente { get; set; }

        public virtual GroupeItem IdGroupeNavigation { get; set; }
        public virtual ICollection<Item> Item { get; set; }
    }
}