// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models
{
    public partial class TypeItem
    {
        public TypeItem()
        {
            Item = new HashSet<Item>();
        }

        public int IdTypeItem { get; set; }
        public int Nom { get; set; }
        public int Prix { get; set; }

        public virtual ICollection<Item> Item { get; set; }
    }
}